In [1]:
path = ".."
# generate txt files for each iol_yyyy and each model (gpt4, gpt3.5, gpt4o, claude3.5s, claude3o, claude3h)

import os
import sys

sys.path.append(path)
for i in range(2003, 2007):
    for model in ["gpt4", "gpt3.5", "gpt4o", "claude3.5s", "claude3o", "claude3h"]:
        os.system(f"touch {path}/iol_{i}/iol_{i}_{model}.txt")
        print(f"touch {path}/iol_{i}/iol_{i}_{model}.txt")

touch ../iol_2003/iol_2003_gpt4.txt
touch ../iol_2003/iol_2003_gpt3.5.txt
touch ../iol_2003/iol_2003_gpt4o.txt
touch ../iol_2003/iol_2003_claude3.5s.txt
touch ../iol_2003/iol_2003_claude3o.txt
touch ../iol_2003/iol_2003_claude3h.txt
touch ../iol_2004/iol_2004_gpt4.txt
touch ../iol_2004/iol_2004_gpt3.5.txt
touch ../iol_2004/iol_2004_gpt4o.txt
touch ../iol_2004/iol_2004_claude3.5s.txt
touch ../iol_2004/iol_2004_claude3o.txt
touch ../iol_2004/iol_2004_claude3h.txt
touch ../iol_2005/iol_2005_gpt4.txt
touch ../iol_2005/iol_2005_gpt3.5.txt
touch ../iol_2005/iol_2005_gpt4o.txt
touch ../iol_2005/iol_2005_claude3.5s.txt
touch ../iol_2005/iol_2005_claude3o.txt
touch ../iol_2005/iol_2005_claude3h.txt
touch ../iol_2006/iol_2006_gpt4.txt
touch ../iol_2006/iol_2006_gpt3.5.txt
touch ../iol_2006/iol_2006_gpt4o.txt
touch ../iol_2006/iol_2006_claude3.5s.txt
touch ../iol_2006/iol_2006_claude3o.txt
touch ../iol_2006/iol_2006_claude3h.txt

In [1]:
path = "../iol_samples"
# generate txt files for each iol_yyyy and each model (gpt4, gpt3.5, gpt4o, claude3.5s, claude3o, claude3h)

import os
import sys

sys.path.append(path)
for i in ['vision','text']:
    for model in ["gpt4", "gpt4om", "gpt4o", "claude3.5s", "claude3o", "claude3h", "gemini1.5p","o1strawberry"]:
        os.system(f"mkdir {path}/{i}/{model}")
        print(f"mkdir {path}/{i}/{model}")
        os.system(f"touch {path}/{i}/{model}/'response'.txt")
        print(f"touch {path}/{i}/{model}/'response'.txt")
        os.system(f"touch {path}/{i}/{model}/'evaluation'.txt")
        print(f"touch {path}/{i}/{model}/'evaluation'.txt")

mkdir ../iol_samples/vision/gpt4
touch ../iol_samples/vision/gpt4/'response'.txt
touch ../iol_samples/vision/gpt4/'evaluation'.txt
mkdir ../iol_samples/vision/gpt4om
touch ../iol_samples/vision/gpt4om/'response'.txt
touch ../iol_samples/vision/gpt4om/'evaluation'.txt
mkdir ../iol_samples/vision/gpt4o
touch ../iol_samples/vision/gpt4o/'response'.txt
touch ../iol_samples/vision/gpt4o/'evaluation'.txt
mkdir ../iol_samples/vision/claude3.5s
touch ../iol_samples/vision/claude3.5s/'response'.txt
touch ../iol_samples/vision/claude3.5s/'evaluation'.txt
mkdir ../iol_samples/vision/claude3o
touch ../iol_samples/vision/claude3o/'response'.txt
touch ../iol_samples/vision/claude3o/'evaluation'.txt
mkdir ../iol_samples/vision/claude3h
touch ../iol_samples/vision/claude3h/'response'.txt
touch ../iol_samples/vision/claude3h/'evaluation'.txt
mkdir ../iol_samples/vision/gemini1.5p
touch ../iol_samples/vision/gemini1.5p/'response'.txt
touch ../iol_samples/vision/gemini1.5p/'evaluation'.txt
mkdir ../iol_samples/vision/o1strawberry
touch ../iol_samples/vision/o1strawberry/'response'.txt
touch ../iol_samples/vision/o1strawberry/'evaluation'.txt
mkdir ../iol_samples/text/gpt4
touch ../iol_samples/text/gpt4/'response'.txt
touch ../iol_samples/text/gpt4/'evaluation'.txt
mkdir ../iol_samples/text/gpt4om
touch ../iol_samples/text/gpt4om/'response'.txt
touch ../iol_samples/text/gpt4om/'evaluation'.txt
mkdir ../iol_samples/text/gpt4o
touch ../iol_samples/text/gpt4o/'response'.txt
touch ../iol_samples/text/gpt4o/'evaluation'.txt
mkdir ../iol_samples/text/claude3.5s
touch ../iol_samples/text/claude3.5s/'response'.txt
touch ../iol_samples/text/claude3.5s/'evaluation'.txt
mkdir ../iol_samples/text/claude3o
touch ../iol_samples/text/claude3o/'response'.txt
touch ../iol_samples/text/claude3o/'evaluation'.txt
mkdir ../iol_samples/text/claude3h
touch ../iol_samples/text/claude3h/'response'.txt
touch ../iol_samples/text/claude3h/'evaluation'.txt
mkdir ../iol_samples/text/gemini1.5p
touch ../iol_samples/text/gemini1.5p/'response'.txt
touch ../iol_samples/text/gemini1.5p/'evaluation'.txt
mkdir ../iol_samples/text/o1strawberry
touch ../iol_samples/text/o1strawberry/'response'.txt
touch ../iol_samples/text/o1strawberry/'evaluation'.txt

In [2]:
import pandas as pd

years = [str(i) for i in range(2004, 2024)]
# remove 2020
years.remove('2020')

models = ["gpt4o", "claude3.5s", "claude3o", "claude3h", "gemini1.5p", "gpt4", "gpt4om"]

eval_table = pd.DataFrame(columns=["Year", "Model", "Total Score", "Total Possible", "Accuracy", "Total Questions", "Type 1 Right", "Type 1 Possible", "Type 2 Right", "Type 2 Possible", "Type 3 Right", "Type 3 Possible"])

# add blank rows to eval_table
for year in years:
    for model in models:
        eval_table = pd.concat([eval_table, pd.DataFrame([[year, model, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], columns=["Year", "Model", "Total Score", "Total Possible", "Accuracy", "Total Questions", "Type 1 Right", "Type 1 Possible", "Type 2 Right", "Type 2 Possible", "Type 3 Right", "Type 3 Possible"])], ignore_index=True)

In [3]:
eval_table

,Year,Model,Total Score,Total Possible,Accuracy,Total Questions,Type 1 Right,Type 1 Possible,Type 2 Right,Type 2 Possible,Type 3 Right,Type 3 Possible
0,2004,gpt4o,0,0,0,0,0,0,0,0,0,0
1,2004,claude3.5s,0,0,0,0,0,0,0,0,0,0
2,2004,claude3o,0,0,0,0,0,0,0,0,0,0
3,2004,claude3h,0,0,0,0,0,0,0,0,0,0
4,2004,gemini1.5p,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
128,2023,claude3o,0,0,0,0,0,0,0,0,0,0
129,2023,claude3h,0,0,0,0,0,0,0,0,0,0
130,2023,gemini1.5p,0,0,0,0,0,0,0,0,0,0
131,2023,gpt4,0,0,0,0,0,0,0,0,0,0
132,2023,gpt4om,0,0,0,0,0,0,0,0,0,0

In [3]:
for i in range(2007, 2024):
    os.system(f"mv ../iol_{i}/o1strawberry/responses.txt ../iol_{i}/o1strawberry/iol_{i}_o1strawberry.txt")
    print(f"mv ../iol_{i}/o1strawberry/responses.txt ../iol_{i}/o1strawberry/iol_{i}_o1strawberry.txt")

mv ../iol_2007/o1strawberry/responses.txt ../iol_2007/o1strawberry/iol_2007_o1strawberry.txt
mv ../iol_2008/o1strawberry/responses.txt ../iol_2008/o1strawberry/iol_2008_o1strawberry.txt
mv ../iol_2009/o1strawberry/responses.txt ../iol_2009/o1strawberry/iol_2009_o1strawberry.txt
mv ../iol_2010/o1strawberry/responses.txt ../iol_2010/o1strawberry/iol_2010_o1strawberry.txt
mv ../iol_2011/o1strawberry/responses.txt ../iol_2011/o1strawberry/iol_2011_o1strawberry.txt
mv ../iol_2012/o1strawberry/responses.txt ../iol_2012/o1strawberry/iol_2012_o1strawberry.txt
mv ../iol_2013/o1strawberry/responses.txt ../iol_2013/o1strawberry/iol_2013_o1strawberry.txt
mv ../iol_2014/o1strawberry/responses.txt ../iol_2014/o1strawberry/iol_2014_o1strawberry.txt
mv ../iol_2015/o1strawberry/responses.txt ../iol_2015/o1strawberry/iol_2015_o1strawberry.txt
mv ../iol_2016/o1strawberry/responses.txt ../iol_2016/o1strawberry/iol_2016_o1strawberry.txt
mv ../iol_2017/o1strawberry/responses.txt ../iol_2017/o1strawberry/iol_2017_o1strawberry.txt
mv ../iol_2018/o1strawberry/responses.txt ../iol_2018/o1strawberry/iol_2018_o1strawberry.txt
mv ../iol_2019/o1strawberry/responses.txt ../iol_2019/o1strawberry/iol_2019_o1strawberry.txt
mv ../iol_2020/o1strawberry/responses.txt ../iol_2020/o1strawberry/iol_2020_o1strawberry.txt
mv ../iol_2021/o1strawberry/responses.txt ../iol_2021/o1strawberry/iol_2021_o1strawberry.txt
mv ../iol_2022/o1strawberry/responses.txt ../iol_2022/o1strawberry/iol_2022_o1strawberry.txt
mv ../iol_2023/o1strawberry/responses.txt ../iol_2023/o1strawberry/iol_2023_o1strawberry.txt

mv: rename ../iol_2020/o1strawberry/responses.txt to ../iol_2020/o1strawberry/iol_2020_o1strawberry.txt: No such file or directory